export const products = [
   {
      id: 'returnji-sticker',
      name: 'Returnji QR Stickers',
      description: 'A durable, weather-resistant QR sticker that helps lost items find their way back to you. Perfect for bottles, notebooks, laptops, bags, and other everyday essentials.',
      price: 29.00,
      image: '/returnji_sticker.jpg',
      badge: 'Best Seller',
      badgeColor: 'bg-teal-100 text-teal-700',
   },
   {
      id: 'returnji-keychain',
      name: 'Returnji QR Keychain',
      description: 'A premium QR-enabled keychain designed for keys, backpacks, luggage, and valuables. If found, anyone can scan the QR code and securely help return your item.',
      price: 89.00,
      image: '/returnji_keychain.jpg',
      badge: 'Premium',
      badgeColor: 'bg-indigo-100 text-indigo-700',
   },
   {
      id: 'returnji-bundle',
      name: 'Returnji Bundle',
      description: 'The complete protection pack for travelers and everyday users. Includes 2 Returnji QR Keychains and 8 QR Stickers to safeguard all your important belongings.',
      price: 369.00,
      image: '/returnji_bundle.jpg',
      badge: 'Save 10%',
      badgeColor: 'bg-blue-100 text-blue-700',
   },
   {
      id: 'returnji-student-bundle',
      name: 'Returnji Student Bundle',
      description: 'Designed for students who carry multiple essentials every day. Includes 8 QR Stickers and 1 QR keychain to protect water bottles, notebooks, calculators, ID card holders, and more.',
      price: 249,
      image: '/returnji_student_bundle.jpg',
      badge: 'Bundle Save 20%',
   },
   {
      id: 'returnji-custom-sticker',
      name: 'Customize Your QR-Sticker',
      description: 'Create a QR sticker thats uniquely yours. Personalize it with custom colors, designs, logos, and themes while keeping Returnjis smart recovery technology built in.',
      price: 29.00,
      image: '/returnji_custom_sticker.png',
      badge: 'New Arrival',
      badgeColor: 'bg-emerald-100 text-emerald-700',
   },
   {
      id: 'returnji-custom-keychain',
      name: 'Customize Your QR-Keychain',
      description: 'Design a one-of-a-kind QR keychain with your favorite colors, photos, artwork, or branding. Combine personal style with powerful lost-and-found protection.',
      price: 129.00,
      image: '/returnji_custom_keychain.png',
      badge: 'New Arrival',
      badgeColor: 'bg-emerald-100 text-emerald-700',
   },
];
